# Create all loggers
logger.WorkflowDeleteWebScript.name=com.sergio.psc.WorkflowDeleteWebScript
logger.WorkflowDeleteWebScript.level=info
logger.WorkflowDeployWebScript.name=com.sergio.psc.WorkflowDeployWebScript
logger.WorkflowDeployWebScript.level=info
logger.WorkflowGetWebScript.name=com.sergio.psc.WorkflowGetWebScript
logger.WorkflowGetWebScript.level=info
logger.WorkflowListWebScript.name=com.sergio.psc.WorkflowListWebScript
logger.WorkflowListWebScript.level=info